[package]
name = "xerg-api"
version = "0.1.0"
edition = "2021"

[dependencies]
async-graphql = "5.0"
chrono = { version = "0.4.23", features = ["serde"] }
async-graphql-actix-web = "5.0"
actix-web = "4.0"
tokio = { version = "1.0", features = ["full"] }
mongodb = "2.3.0"
uuid = { version = "1", features = ["serde", "v4"] }
